--과제 13번

--Q1.
DROP TABLE EMPIDX;
CREATE TABLE EMPIDX
AS SELECT  * FROM EMP;


SELECT * FROM EMPIDX;

CREATE INDEX IDX_EMPIDX_EMPNO on EMPIDX (EMPNO);

SELECT * FROM USER_INDEXES
WHERE INDEX_NAME = 'IDX_EMPIDX_EMPNO';

--Q2.

CREATE OR REPLACE VIEW EMPIDX_OVER15K
AS
SELECT EMPNO as EMPNO , ENAME as ENAME,JOB as JOB,DEPTNO AS DEPTNO,SAL,NVL2(COMM,'O','X') AS COMM
FROM EMPIDX
WHERE EMPIDX.SAL > 1500;


SELECT * FROM EMPIDX_OVER15K;

--Q3.
--1
CREATE TABLE DEPTSEQ
AS SELECT * FROM DEPT;

SELECT * FROM DEPTSEQ;

--2
CREATE SEQUENCE DEPTSEQ_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 99
MINVALUE 1
NOCYCLE
NOCACHE;
--3
INSERT INTO DEPTSEQ
VALUES (DEPTSEQ_SEQ.nextval,'DATABASE','SEOUL');

INSERT INTO DEPTSEQ
VALUES (DEPTSEQ_SEQ.nextval,'WEB','BUSAN');

INSERT INTO DEPTSEQ
VALUES (DEPTSEQ_SEQ.nextval,'MOBILE','ILSAN');

SELECT * FROM DEPTSEQ;
SELECT * FROM USER_SEQUENCES;


-------------------- Q4.? 2) 제약조건 과제
SELECT * FROM TAB;

DROP TABLE STUDENT;
DROP TABLE UNIVDEPT;

CREATE TABLE STUDENT(
    ID NUMBER(9) CHECK ( LENGTH(ID)=8 ),
    NAME VARCHAR(10),
    BIRTHDAY DATE,
    PHONENUM VARCHAR(20) CHECK ( LENGTH(PHONENUM) > 11 ),
    GRADE NUMBER(1) DEFAULT 1 CHECK ( GRADE BETWEEN 1 and 4),
    SEMSTER NUMBER(1) DEFAULT 1 check ( SEMSTER BETWEEN 1 and 2),
    DEPTNO VARCHAR(5) check ( LENGTH(DEPTNO) = 3 and UPPER(DEPTNO)  BETWEEN 'A' and 'Z' ),
    CONSTRAINT ID_PK PRIMARY KEY (ID),
    CONSTRAINT DEPTNO_FK FOREIGN KEY (DEPTNO)
    REFERENCES UNIVDEPT(DEPTNO) ON DELETE SET NULL

);

CREATE TABLE UNIVDEPT(
    DEPTNO VARCHAR(10) check ( LENGTH(DEPTNO) = 3 and UPPER(DEPTNO)  BETWEEN 'A' and 'Z' ),
    DEPTNAME VARCHAR(10),
    ESTDATE DATE,
    DEPTTEL VARCHAR(20) check ( LENGTH(DEPTTEL)> 11 ),
    CONSTRAINT DEPTNO_PK PRIMARY KEY (DEPTNO)



);
---------------------- 테이블은 생성된 상태 퀴즈 풀자 이제 
--Q1
SELECT * FROM STUDENT;
SELECT* FROM UNIVDEPT;
--Q2
INSERT INTO STUDENT (ID, NAME, BIRTHDAY, PHONENUM,DEPTNO)
VALUES (11111112,'홍길동',TO_DATE('1998/02/03','YYYY/MM/DD'),
        '010-8323-6134','SAV');

-- 외래키를 지정하지 않은 상태에서 지정할려 할시 외래키를 입력할수 없다
--외래키를 먼저 생성하자
INSERT INTO UNIVDEPT
VALUES ('SAV','우왕',sysdate,'010-8323-6134');
--다시 위에 STUDENT 데이터 입력을 하자

--Q3.
INSERT INTO STUDENT (ID)
VALUES (11111111);

SELECT * FROM STUDENT;
-- ID 만 넣었지만 디폴트 값을 볼수 있음 !
--Q4.
INSERT INTO STUDENT (ID)
VALUES (111111111);
--8자리 이상 올수 없다..!

--Q5.
INSERT INTO UNIVDEPT(DEPTNO)
VALUES ('1AV');

--학과 번호에는 숫자가들어올수없다!

--Q6.
SELECT * FROM USER_CONSTRAINTS
WHERE TABLE_NAME in ('STUDENT','UNIVDEPT');


