--과제 13번

--Q1.
DROP TABLE EMPIDX;
CREATE TABLE EMPIDX
AS SELECT  * FROM EMP;


SELECT * FROM EMPIDX;

CREATE INDEX IDX_EMPIDX_EMPNO on EMPIDX (EMPNO);

SELECT * FROM USER_INDEXES
WHERE INDEX_NAME = 'IDX_EMPIDX_EMPNO';

--Q2.

CREATE OR REPLACE VIEW EMPIDX_OVER15K
AS
SELECT EMPNO as EMPNO , ENAME as ENAME,JOB as JOB,DEPTNO AS DEPTNO,SAL,NVL2(COMM,'O','X') AS COMM
FROM EMPIDX
WHERE EMPIDX.SAL > 1500;


SELECT * FROM EMPIDX_OVER15K;

--Q3.

CREATE TABLE DEPTSEQ
AS SELECT * FROM DEPT;

SELECT * FROM DEPTSEQ;

CREATE SEQUENCE DEPTSEQ_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 99
MINVALUE 1
NOCYCLE
NOCACHE;

INSERT INTO DEPTSEQ
VALUES (DEPTSEQ_SEQ.nextval,'DATABASE','SEOUL');

INSERT INTO DEPTSEQ
VALUES (DEPTSEQ_SEQ.nextval,'WEB','BUSAN');

INSERT INTO DEPTSEQ
VALUES (DEPTSEQ_SEQ.nextval,'MOBILE','ILSAN');

SELECT * FROM DEPTSEQ;
SELECT * FROM USER_SEQUENCES;


--------------------2) 제약조건 과제
SELECT * FROM TAB;

DROP TABLE STUDENT;

CREATE TABLE STUDENT(
    ID NUMBER(8) CHECK ( LENGTH(ID)=8 ),
    NAME VARCHAR(10),
    BIRTHDAY DATE,
    PHONENUM VARCHAR(20) CHECK ( LENGTH(PHONENUM) > 11 ),
    GRADE NUMBER(1) DEFAULT 1 CHECK ( GRADE BETWEEN 1 and 4),
    SEMSTER NUMBER(1) DEFAULT 1 check ( SEMSTER BETWEEN 1 and 2),
    DEPTNO VARCHAR(3) check ( LENGTH(DEPTNO) = 3 and DEPTNO NOT BETWEEN 0 and 9 ),
    CONSTRAINT ID_PK PRIMARY KEY (ID),
    CONSTRAINT DEPTNO_FK FOREIGN KEY (DEPTNO)
    REFERENCES UNIVDEPT(DEPTNO) ON DELETE SET NULL

);

CREATE TABLE UNIVDEPT(
    DEPTNO VARCHAR(3) check ( LENGTH(DEPTNO) = 3 and DEPTNO  NOT  BETWEEN 0 and 9 ),
    DEPTNAME VARCHAR(10),
    ESTDATE DATE,
    DEPTTEL VARCHAR(20) check ( LENGTH(DEPTTEL)> 11 ),
    CONSTRAINT DEPTNO_PK PRIMARY KEY (DEPTNO)

);
---------------------- 테이블은 생성된 상태 퀴즈 풀자 이제 
--Q1.


