/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.70
 * Generated at: 2021-08-24 07:58:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class _01_005fimplicitObject_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- 내부 객체 \r\n");
      out.write("(Implicit Object, 암시적인 객체, 내장/jsp 기본객체)\r\n");
      out.write("\r\n");
      out.write("	: 프로그래밍을 단순화시키기 위해서\r\n");
      out.write("	별다른 선언 과정 없이 객체 사용할 수 있는 객체\r\n");
      out.write("	: JSP 컨테이너가 제공\r\n");
      out.write("	\r\n");
      out.write("	request\r\n");
      out.write("	: 사용자 요청 (request)에 대한 정보 처리하기 위한 객체\r\n");
      out.write("	\r\n");
      out.write("	exception\r\n");
      out.write("	: jsp 페이지가 에러 페이지로 지정될 때 만들어지는 객체\r\n");
      out.write("	: 일반적인 jsp 페이지 X\r\n");
      out.write("	\r\n");
      out.write("	내부 객체 종류\r\n");
      out.write("	1) 입출력 관련\r\n");
      out.write("	2) 정보 제공\r\n");
      out.write("	3) 서블릿 관련\r\n");
      out.write("	4) 예외 처리 관련\r\n");
      out.write("	\r\n");
      out.write("	1-1) request\r\n");
      out.write("	: 파라미터를 포함한 사용자 요청 담고 있는 객체\r\n");
      out.write("	: javax.servlet.http.HttpServletRequest\r\n");
      out.write("	\r\n");
      out.write("	ex) request.getParameter()\r\n");
      out.write("		request.setCharacterEncoding()\r\n");
      out.write(" -->\r\n");
      out.write(" <h1>Request Example</h1>\r\n");
      out.write(" <form method=\"post\" action=\"02_request.jsp\">\r\n");
      out.write(" 	Name: <input name=\"name\"><br/>\r\n");
      out.write(" 	Student Number: <input name=\"stuNum\"><br/>\r\n");
      out.write(" 	Gender: Male <input type=\"radio\" name=\"gender\" value=\"male\" checked>\r\n");
      out.write(" 			Female <input type=\"radio\" name=\"gender\" value=\"female\">\r\n");
      out.write(" 	<br/>\r\n");
      out.write(" 	Major: <select name=\"major\">\r\n");
      out.write(" 		<option value=\"korean\" selected>korean</option>\r\n");
      out.write(" 		<option value=\"english\">english</option>\r\n");
      out.write(" 		<option value=\"math\">math</option>\r\n");
      out.write(" 		<option value=\"politics\">politics</option>\r\n");
      out.write(" 		<option value=\"physics\">physics</option>\r\n");
      out.write(" 	</select><br/>\r\n");
      out.write(" <input type=\"submit\" value=\"sent\">\r\n");
      out.write(" </form>\r\n");
      out.write(" \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
